# -*- coding: utf-8 -*-
"""generate database

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WkceiJAYz4aXpwg6UL6-5OJxfG-6rD9l
"""

# product database
# Three table for the on the firebase
"""
TABLE products
productName, 
productHashID, 
productPhoto, 
productDescription, 
productStyles, 
shippingInfo,
productCompanyID
productCompanyName
"""
"""
TABLE companies
companyName,
companyHashID,
companyPassword,
companyPhoto,
companyDescription,
companyPhone,
companyEmail,
companyWebsite,
companyOfficeAddress,
companyPostal
"""

"""
TABLE users
userHashID,
userPhoto,
userName,
userPassword,
userPhone,
userEmail,
userAddress,
<Gender, Age>
"""

import json
import random

def java_string_hashcode(s):
    h = 0
    for c in s:
        h = (31 * h + ord(c)) & 0xFFFFFFFF
    return ((h + 0x80000000) & 0xFFFFFFFF) - 0x80000000

funiture_words = ["table", "chair", "bed", "cupboard", "cabinetry", "desk", "chest", 
            "bookcase", "sideboard", "closet", "lamp", "couch", "shelf", "matress"]
material_words = ["leather", "wooden", "fabric", "wool"]
companyname_words = ["Kexin's","Yinghui's","Yan's","Bonjoon's","Kevin's","Tommy's","Tianyi's"]
companytype_words = ["shop", "Company","Store"," ","Boutique","House", "Workshop", "Antique"]
address_words = ["Plymouth Rd.", "Huron Rd."]
style_words = ["lovely", "baby", "luxury", "effective", "sale"]
shippingInfo_words = ["free shipping", "free shipping over 25 dollars", "$8 dollars"]

# start generating the company table
company_num = 5
company_dict = {}
"""
TABLE companies
companyName,
companyHashID,
companyPassword,
companyPhoto,
companyDescription,
companyPhone,
companyEmail,
companyWebsite,
companyOfficeAddress,
companyPostal
"""
for i in range(company_num):
  print(i)
  company = {}
  company["companyName"] = random.choice(companyname_words) + " "+ random.choice(companytype_words)
  company["companyHashID"] = str(java_string_hashcode(company["companyName"]))
  company["companyPassword"] = "password**"
  company["companyPhoto"] = "imgurl**"
  company["companyDescription"] = "description****"
  company["companyPhone"] = random.choice(range(1000000000,9999999999))
  company["companyEmail"] = company["companyName"].replace(" ","_").replace("'","") + "@arapp.com"
  company["companyWebsite"] = company["companyName"].replace(" ","_").replace("'","") + random.choice([".com",".org",".cn"])
  company["companyOfficeAddress"] = str(random.choice(range(1000,9999))) + " " + random.choice(address_words)
  company["companyPostal"] = str(48)+str(random.choice(range(100,999)))
  print(company["companyHashID"])
  company_dict[company["companyHashID"]] = company

print(company_dict)
with open('companies.json', 'w') as outfile:
  json.dump(company_dict, outfile)
from google.colab import files
files.download("companies.json")

# start generating the products table
product_num = 5
product_dict = {}
"""
TABLE products
productName, 
productHashID, 
productPhoto, 
productDescription, 
productStyles, 
shippingInfo,
productCompanyID
productCompanyName
"""
for i in range(product_num):
  product = {}
  product["productName"] = random.choice(material_words) + " "+ random.choice(funiture_words)
  product["productHashID"] = str(java_string_hashcode(product["productName"]))
  product["productPhoto"] = "imgurl**"
  product["productDescription"] = "description****"
  product["productStyles"] = random.choice(style_words)
  product["shippingInfo"] = random.choice(shippingInfo_words)
  product["productCompanyID"] = random.choice(list(company_dict.keys()))
  product["productCompanyName"] = company_dict[product["productCompanyID"]]["companyName"]
  product_dict[product["productHashID"]] = product

print(product_dict)
with open('products.json', 'w') as outfile:
  json.dump(product_dict, outfile)
from google.colab import files
files.download("products.json")

user_num = 10
user_dict = {}
"""
TABLE users
userName,
userHashID,
userPassword,
userPhoto,
userPhone,
userEmail,
userAddress,
<Gender, Age>
"""
for i in range(user_num):
  user = {}
  user["userName"] = random.choice(material_words) + " "+ random.choice(funiture_words)
  user["userHashID"] = str(java_string_hashcode(user["userName"]))
  user["userPassword"] = "password**"
  user["userPhoto"] = "imgurl**"
  user["userPhone"] = random.choice(range(1000000000,9999999999))
  user["userEmail"] = user["userName"].replace(" ","_").replace("'","") + "@gmail.com"
  user["userAddress"] = str(random.choice(range(1000,9999))) + " " + random.choice(address_words)
  user_dict[user["userHashID"]] = user

print(user_dict)
with open('users.json', 'w') as outfile:
  json.dump(user_dict, outfile)
from google.colab import files
files.download("users.json")